### ISSUE TITLE
[FE] styled-components 적용

### ISSUE THREAD

**Issue by theoldtree** [petlab-dev/app-prototype#12]
- [x] https://styled-components.com/docs/ 에 따라 설치
- [x] styled component 적용

**Comment by theoldtree** [comment]
issue-9 브랜치는 package.json 파일이 이상하게 작동해서 파일옮기고 새로 설치한 후 styled-component 파일 설치 했습니다.

**Comment by dididy** [comment]
바톤 터치 후 적용 완료.
